INSERT INTO writers(first_name, last_name, age, bio)
VALUES('Maria', 'Aldapa', 24, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('James', 'Reid', 32, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('Jess', 'Christensen', 33, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('Oliver', 'Germaine', 5, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('Blake', 'Obuchowski', 34, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');

INSERT INTO platforms(display_name, description)
VALUES ('Political News', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('Sci-Fi Movies', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('Horror Youtube Channel', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('The Cooking Channel', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
('History on TV', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');

INSERT INTO users(email, writer_id, platform_id, password, image_url, address_1, address_2, city, state, postal_code, phone, twitter_username, facebook_username, youtube_username, is_admin)
VALUES ('scifi-movies@scifi.com', NULL, 2, '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q', 'https://miro.medium.com/max/8000/1*JrHDbEdqGsVfnBYtxOitcw.jpeg', '23 Cotton Candy Dr.', NULL, 'Tampa', 'Florida', 54356, '543-434-5432', 'scifi', 'scifi', 'scifi', FALSE),
('jreidmke@gmail.com', 2, NULL, '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q', 'https://searchengineland.com/figz/wp-content/seloads/2018/09/writer-writing-ss-1920.jpg', '3180 S. Brust Ave.', 'Apt. 202', 'Milwaukee', 'Wisconsin', 53202, '630-338-5693', NULL, NULL, 'jreidmke', TRUE),
('jessc@church.com', 3, NULL, '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q', 'https://searchengineland.com/figz/wp-content/seloads/2018/09/writer-writing-ss-1920.jpg', '123 Fake St.', NULL, 'Milwaukee', 'Wisconsin', 42364, '632-231-5431', 'jessc', 'jessc', 'jessc', FALSE),
('ollieg@gmail.com', 4, NULL, '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q', 'https://searchengineland.com/figz/wp-content/seloads/2018/09/writer-writing-ss-1920.jpg', '724 Cool Dude Way', NULL, 'Milwaukee', 'Wisconsin', 42364, '326-435-1243', NULL, NULL, NULL, FALSE),
('blakers@blake.gov', 5, NULL, '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q', 'https://searchengineland.com/figz/wp-content/seloads/2018/09/writer-writing-ss-1920.jpg', '345 Rice Ave', 'Apt. 436', 'Chicago', 'Illinois', 60134, '643-432-6432', NULL, NULL, NULL, FALSE),
('polinews@political-news.com', NULL, 1, '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q', 'https://miro.medium.com/max/8000/1*JrHDbEdqGsVfnBYtxOitcw.jpeg', '46 Business Way', 'Suite 643', 'Chicago', 'Illinois', 53423, '543-453-3242', 'political-news', 'political-news', 'political-news', FALSE),
('mariaaaldapa@gmail.com', 1, NULL, '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q', 'https://searchengineland.com/figz/wp-content/seloads/2018/09/writer-writing-ss-1920.jpg', '224 S. 27th St.', NULL, 'Milwaukee', 'Wisonsin', 52395, '414-399-1206', 'tessaract', 'tessaract', 'tessaract', FALSE),
('horror@horrorshow.com', NULL, 3, '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q', 'https://miro.medium.com/max/8000/1*JrHDbEdqGsVfnBYtxOitcw.jpeg', '432 So Scary Blvd', NULL, 'Tampa', 'Florida', 54356, '543-434-5432', 'horror', 'horror', 'horror', FALSE),
('goodfood@cooking.com', NULL, 4, '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q', 'https://miro.medium.com/max/8000/1*JrHDbEdqGsVfnBYtxOitcw.jpeg', '432 So Tasty Blvd', NULL, 'Altoona', 'Iowa', 54356, '543-434-5442', 'food', 'food', 'food', FALSE),
('history@history.gov', NULL, 5, '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q', 'https://miro.medium.com/max/8000/1*JrHDbEdqGsVfnBYtxOitcw.jpeg', '432 So Historical Blvd', NULL, 'Geneva', 'Illinois', 54356, '543-434-5842', 'history', 'history', 'history', TRUE);

INSERT INTO portfolios(writer_id, title)
VALUES(1, 'Recipes'), (1, 'Politics'), (2, 'Funny Stuff'), (2, 'Scary Stuff'), (2, 'Future Stuff'), (3, 'Religion'), (3, 'Football'), (4, 'Pokemon'), (4, 'Trucks'), (4, 'Parents'), (5, 'History'), (5, 'Theory');

INSERT INTO pieces(writer_id, title, text)
VALUES(1, 'Chickend Soup', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(1, 'Pizza', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(1, 'Kamala and Me', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(2, 'Clown Stuff', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(2, 'Seinfeld', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(2, 'Scariest Tales', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(2, 'Spiders!', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(2, 'Lazers', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(2, 'Star Wars', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(3, 'Learning about The Cross', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(3, 'Communion', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(3, 'Reggie White', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(3, 'Aaron Rodgers', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(4, 'Catching Mewtwo', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(4, 'Snorlax', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(4, 'The Smallest Trucks', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(4, 'The Biggest Trucks', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(4, 'Mom and Dad', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(5, 'Lincoln and LBJ', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(5, 'WFB', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'),
(5, 'The Prince', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');

INSERT INTO gigs (platform_id, title, description, compensation, is_remote, word_count, is_active)
VALUES(1, 'Political Interview', 'Interview this Politician and write us a story', 50.00, TRUE, 2000, TRUE),
(1, 'Political Ideas', 'Tell us how to solve taxes', 100, TRUE, 5000, TRUE),
(2, 'Star Wars Sequel', 'Write a new Star Wars', 200, TRUE, 10000, FALSE),
(2, 'Stargate Reboot', 'Finally, a SG Reboot Returns!', 600, TRUE, 50000, FALSE),
(3, 'Freddy Krueger', 'Interview Robert Englund', 700, TRUE, 100000, TRUE),
(3, 'Spider Movie', 'Write a scary movie about spiders.', 234, TRUE, 2432, TRUE),
(4, 'Pizza Recipe', 'How do you make pizza?', 543, TRUE, 432, TRUE),
(4, 'Goulash', 'How about this? Can you make this', 543, TRUE, 234, TRUE),
(5, 'Civil War', 'Write about how the civil war happend', 521, TRUE, 943, TRUE),
(5, 'WW2', 'How did WWII go down', 534, TRUE, 75, TRUE);


INSERT INTO tags (title, is_fiction)
VALUES('cooking', FALSE), ('food', FALSE), ('recipes', FALSE), ('political comedy', FALSE), ('political history', FALSE), ('politics', FALSE), ('sitcom', TRUE), ('stand up comedy', FALSE), ('humor', TRUE), ('true crime', TRUE), ('monsters', FALSE), ('slashers', TRUE), ('space tech', FALSE), ('sci-fi', TRUE), ('gaming', FALSE), ('automobiles', FALSE), ('trucks', FALSE), ('parenting', FALSE), ('religion studies', FALSE), ('sports', FALSE);

INSERT INTO applications (gig_id, writer_id, portfolio_id, status)
VALUES(1, 1, 2, 'Pending'), (1, 5, 12, 'Pending'), (2, 1, 2, 'Pending'), (2, 5, 12, 'Pending'), (3, 2, 5, 'Accepted'), (4, 2, 5, 'Rejected'), (5, 2, 4, 'Pending'), (6, 2, 4, 'Accepted'), (7, 1, 1, 'Accepted'), (8, 1, 1, 'Rejected'), (9, 5, 11, 'Pending'), (9, 5, 11, 'Pending');

INSERT INTO piece_portfolios (portfolio_id, piece_id)
VALUES(1, 1), (1, 2), (2, 3), (3, 4), (3, 5), (4, 6), (4, 7), (5, 8), (5, 9), (6, 10), (6, 11), (7, 12), (7, 13), (8, 14), (8, 15), (9, 16), (9, 17), (10, 18), (11, 19), (11, 20), (12, 21);

INSERT INTO piece_tags (piece_id, tag_id)
VALUES(1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 6), (4, 8), (4, 9), (5, 8), (6, 11), (6, 12), (7, 11), (7, 12), (8, 13), (8, 14), (9, 19), (10, 19), (11, 20), (12, 20), (13, 14), (14, 14), (15, 16), (16, 16), (17, 17);

INSERT INTO gig_tags (gig_id, tag_id)
VALUES(1, 5), (1, 6), (2, 5), (2, 6), (3, 14), (4, 14), (5, 12), (5, 11), (6, 11), (7, 1), (7, 2), (7, 3), (8, 1), (8, 2), (8, 3), (9, 5), (9, 5);

INSERT INTO platform_tag_follows (platform_id, tag_id)
VALUES(1, 1), (1, 4), (1, 5), (1, 6), (2, 14), (2, 13), (3, 12), (3, 11), (3, 10), (4, 1), (4, 2), (4, 3), (5, 4), (5, 5), (5, 6);

INSERT INTO platform_writer_follows (platform_id, writer_id)
VALUES (1, 1), (1, 5), (2, 2), (3, 2), (4, 1), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5);

INSERT INTO writer_platform_follows(writer_id, platform_id)
VALUES(1, 1), (1, 2), (3, 1), (4, 2), (4, 2), (5, 5), (2, 1), (2, 2), (2, 3), (2, 4);

INSERT INTO writer_tag_follows(writer_id, tag_id)
VALUES(1, 2), (1, 1), (5, 3), (2, 2), (3, 3), (4, 4), (5, 1);