CREATE TABLE tags(
    id SERIAL PRIMARY KEY,
    title VARCHAR UNIQUE NOT NULL,
    is_fiction BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL
);

